---
- hosts: centos
  tasks:
    - name: Update Cache
      yum:
        update_cache: yes

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: "Unconditionally reboot the machine with all defaults"
      reboot:

    - name: "Wait for system to become reachable again"
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: Remove leaf packages
      yum:
        autoremove: yes

    - name: Update Cache
      yum:
        update_cache: yes
