---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: 10.210.210.10
      username: administrator@vsphere.local
      password: ****
      validate_certs: False
      name: Samba01
      template: centos
      datacenter: "TEST DC"
      folder: TEST DC/vm
      guest_id: centos7_64Guest
      state: poweredon
      hardware:
        memory_mb: 4096
        num_cpu: 2
        scsi: paravirtual
      networks:
      - name: "VM Network"
        start_connected: True
        ip: 10.210.210.21
        netmask: 255.255.255.0
        gateway: 10.210.210.1
      customization:
        dns_servers:
        - 10.210.210.18
        - 10.210.210.19
        dns_suffix:
        - test.local
        domain: test.local
        hostname: Samba01
      wait_for_customization: yes
      wait_for_ip_address: yes
    delegate_to: localhost
  - name: Perform storage vMotion and host vMotion of virtual machine
    vmware_vmotion:
      hostname: 10.210.210.10
      username: administrator@vsphere.local
      password: 1234qqqQ*
      validate_certs: no
      vm_name: Samba01
      destination_host: esx02.test.local
      destination_datastore: 12_Local_Large
    delegate_to: localhost

- name: Update Centos Server
  hosts: 10.210.210.21
  tasks:
    - name: Update Cache
      yum:
        update_cache: yes

    - name: Upgrade all Packages
      yum:
        name: '*'
        state: latest

    - name: "Unconditionally reboot the machine with all defaults"
      reboot:

    - name: "Wait for system to become reachable again"
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: Remove leaf packages
      yum:
        autoremove: yes

    - name: Update Cache
      yum:
        update_cache: yes
